package com.staffrakho.dataModel

data class PostJobDataModel(
    val success: String,
    val message: String,
    val data: ArrayList<MyJobs>,
)

data class MyJobs(
    val id: Int,
    val user_id: String,
    val company_id: String,
    val title: String,
    val slug: String,
    val description: String,
    val roles: String,
    val category_id: String,
    val category_name: String,
    val sub_category_name: String,
    val experience_label: String,
    val salary_label: String,
    val state_name: String,
    val city_name: String,
    val position: String,
    val address: String,
    val featured: String,
    val type: String,
    val status: String,
    val last_date: String,
    val pin_code: String,
    val required_skills: String,
    val preferred_call_time: String,
    val phone: String,
    val email: String,
    val whatsapp: String,
    val direct_apply: Int,
    val call_apply: Int,
    val message_apply: Int,
    val whatsapp_apply: Int,
    val number_of_vacancy: String,
    val experience: String,
    val gender: String,
    val salary: String,
    val company_logo: String?,
    val company_name: String?,
    val sub_category_id: String,
    val state_id: String,
    val city_id: String,
    val profile_type: String,
    val created_at: String,
    val applicant_count: String,
    val type_label: String,
    val profile_type_label: String,
    val company_look_label: String,
    val business_type_label: String,
    val gender_label: String,
    val required_education_label: String,
)
